---
title: "University of British Columbia - Okanagan"
author: "Craig Adlam (48226583)"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Date: 2024/02/05  
- Added unit tests to second function analyze_business_sectors  
- Added analyze_cities.Rd & analyze_business_sectors.Rd to 'man' directory  
- Added roxygen2 documentation to analyze_cities.R & analyze_business_sectors.R  
- Debugged mock tests and updated test_main  

Date: 2024/02/03  
- Modified subplots to exclude y-axis ticks and density scales  
- Created corrected example plots (sorted vector fix for plot mapping)  
- Modified code to return both the facetted plot as well as the interactive plot  
--- This allows the user to compare interactively or in separate facetted plots  
- Updated vignette to include example output and new returned values  

Date: 2024/02/02  
- Excluded API key, and environmental variable from function  
- Included plot functions within both 'analyze' functions to return the plot  
--- This ensures the dataframe, parameter list, and plot are returned  
- Added prompts and error handling for incorrect parameters  
--- This ensures parameters must be entered if there is an empty function call  
- Added vignette (unsure if there are to be multiple or one main one)

Date: 2024/02/01  
- Saved multiple images from functionality function calls with different categories  
- Decided to split the AnalyzeRatings function into two separate functions  
--- One for analyzing different cities based on a specific business sector  
--- One for analyzing different business sectors within a specific city  
- Deleted old function from group repo  
- Moved independent journal from individual repo into group repo  

Date: 2024/01/31  
- Ran analyze_ratings function to accept different categories functionality  

Date: 2024/01/30  
- Adjusted function code to accept categories without a price variable  
- Debugged and finalized the plot-related unit tests  

Date: 2024/01/28  
- Discussed/confirmed workflow requirements (Step 2)  
--- This helped ensure we were using branches to push items  
- Reviewed Yelp API function in R code to prepare for testing  
- Created unittests to test the function AnalyzeRatings  
--- Git add, commit, pushed to CraigBranch & merged with main using pull request  
- Created individual repo for individual notebook requirement  
--- Git add, commit, pushed to main from main because only individual task  

Date: 2024/01/25  
- Created function in Python to retrieve data from Yelp  
- Converted to R code once output confirmed  
- Added plotting functionality in R code  
- Git add, commit, push code using CraigBranch  
--- This helped setup an example for group to use when searching businesses  
- Gathered our ideas & wrote proposal for Yelp API  

Date: 2024/01/24  
- Suggested Yelp APIs to group members  
--- This helped contribute to group brainstorming sessions with a new idea   
- Explored Yelp APIs  
- Tested Yelp APIs  
- Brainstormed ideas for wrapping Yelp APIs  

Date: 2024/01/21  
- Explored Covid-19 APIs suggested by group members  
- Explored NHL APIs, tested one in Python  
- Added NHL APIs to brainstorming document  
--- This helped show that request limits were important, trial memberships etc.  

Date: 2024/01/19  
- Looked over project requirements  
- Checked group ideas and code that were discussed on slack  
- Explored PubMed APIs suggested by group members   

Date: 2024/01/15  
- Explored API examples from word document  


